from datetime import datetime
from app import db

class Service(db.Model):
    __tablename__ = 'services'
    
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False, index=True)
    description = db.Column(db.Text)
    category = db.Column(db.String(100), nullable=False)  # EC2, Consulting, Storage, etc.
    
    # Pricing
    pricing_model = db.Column(db.String(20), default='hourly')  # hourly, fixed, monthly
    usd_rate = db.Column(db.Numeric(10, 2))
    inr_rate = db.Column(db.Numeric(10, 2))

    
    # Service details
    unit = db.Column(db.String(20), default='hour')  # hour, month, project, etc.
    is_active = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    invoice_line_items = db.relationship('InvoiceLineItem', backref='service', lazy='dynamic')
    
    @property
    def usage_count(self):
        """Get number of times this service has been used."""
        return self.invoice_line_items.count()
    
    @property
    def total_revenue_usd(self):
        """Get total revenue generated by this service in USD."""
        return sum(item.usd_amount for item in self.invoice_line_items if item.usd_amount)
    
    @property
    def total_revenue_inr(self):
        """Get total revenue generated by this service in INR."""
        return sum(item.inr_amount for item in self.invoice_line_items if item.inr_amount)
    
    def to_dict(self):
        """Convert service to dictionary."""
        return {
            'id': self.id,
            'name': self.name,
            'description': self.description,
            'category': self.category,
            'pricing_model': self.pricing_model,
            'usd_rate': float(self.usd_rate) if self.usd_rate else None,
            'inr_rate': float(self.inr_rate) if self.inr_rate else None,
            'unit': self.unit,
            'is_active': self.is_active,
            'usage_count': self.usage_count,
            'total_revenue_usd': float(self.total_revenue_usd) if self.total_revenue_usd else 0,
            'total_revenue_inr': float(self.total_revenue_inr) if self.total_revenue_inr else 0,
            'created_at': self.created_at.isoformat()
        }
    
    def __repr__(self):
        return f'<Service {self.name}>'